### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by AntoniosBarotsis** [dmcg310/Rust-Traverse#1]
~~Annoyingly I can't copy the text from my terminal when running this project, probably some control sequence does something weird~~ but running the binary (built from source) prints the following:

![image](https://github.com/dmcg310/Rust-Traverse/assets/50240570/62fc6471-b8ef-4497-9f43-c26caa31288d)

The relevant line is [here](https://github.com/dmcg310/Rust-Traverse/blob/fba06741e3f0ddf3c32f36491a670ff47426ed3f/src/ui/display/pane.rs#L61).

This definitely seems to be a windows thing which I'm not sure if you even want to support in the first place. In case you do,
the following works for me: (not that the cmd equivalent of `ls` is [`dir`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/dir))

```rs
use std::process::Command;

fn main() {
  let mut list_dir = Command::new("cmd");
  let output = list_dir.args(["/C", "dir"]).output();
  dbg!(output.unwrap());
}
```

Of course this would probably require you to rewrite the parsing stuff. You could also experiment with spawning a powershell instance instead of a cmd one in case the output is easier to work with (doubt it's much different and it would probably also be slower but just mentioning it here).

**Comment by dmcg310** [comment]
The program hasn't even been tested on windows, I haven't thought about it either, however, if you plan on using the program I will try and make it cross platform

**Comment by AntoniosBarotsis** [comment]
That would be cool :)

I can try and help with both testing and/or implementing certain parts of it given the proper guidance 😅

**Comment by dmcg310** [comment]
Yes sure, if you feel you can implement parts of it now, then go for it. If not I'll try to start it and see where it'll take us
