### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [dmcg310/Rust-Traverse#3]
Do you plan to publish to crates.io so people can install using "cargo install rt"?
(or consider cargo binstall support...).

I looked for it and couldn't find it....if it is published, just let us know the name (and add that as an option to the install section of README?).

**Comment by dmcg310** [comment]
Done! See here:
- [Crates.io](https://crates.io/crates/rst-traverse)

**Comment by andrewdavidmackenzie** [comment]
Thanks!!
maybe align crate and binary and repo names more?
